### ISSUE TITLE
cmake_build.py execute with vs2017 Professional  x64

### ISSUE THREAD

**Issue by marshal-it** [samdauwe/BabylonCpp#71]
////////////////////
Traceback (most recent call last):
  File "D:/GitHub/BabylonCpp/src/Samples/make_samples_info/make_samples_info.py", line 188, in <module>
    write_json_info_file()
  File "D:/GitHub/BabylonCpp/src/Samples/make_samples_info/make_samples_info.py", line 94, in write_json_info_file
    infos = make_all_info()
  File "D:/GitHub/BabylonCpp/src/Samples/make_samples_info/make_samples_info.py", line 89, in make_all_info
    result.append(sample_info(cpp_file))
  File "D:/GitHub/BabylonCpp/src/Samples/make_samples_info/make_samples_info.py", line 51, in sample_info
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 1491: illegal multibyte sequence
/////////////////////////////////
Traceback (most recent call last):
  File "cmake_build.py", line 354, in <module>
    main()
  File "cmake_build.py", line 351, in main
    WindowsBuild()
  File "cmake_build.py", line 293, in __init__
    Build.__init__(self)
  File "cmake_build.py", line 104, in __init__
    getattr(self, args.command)()
  File "cmake_build.py", line 117, in all
    self._cmakeConfigure(args)
  File "cmake_build.py", line 195, in _cmakeConfigure
    self._tools.runCommand(self._buildDir, cmakeCmd)
  File "cmake_build.py", line 65, in runCommand
    subprocess.check_call(command, shell=shell, env=env, cwd=directory)
  File "C:\Users\zhongzhihua01\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
/////////////////////////////////
CMakeError.log
[
D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\src.cxx(1): error C2065: '__deprecated__': undeclared identifier [D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\cmTC_0e117.vcxproj]

D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\src.cxx(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\cmTC_0e117.vcxproj]

D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\src.cxx(1): error C2448: '__attribute__': function-style initializer appears to be a function definition [D:\GitHub\BabylonCpp\release_build\CMakeFiles\CMakeTmp\cmTC_0e117.vcxproj]

]

**Comment by marshal-it** [comment]
had fixed, because git updates no recursive.
